---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
       that: true
  - name: Check NGINX configs
    shell: clickhouse validate --no-environment --config-yaml /etc/clickhouse/clickhouse.yml
  - name: Check NGINX status
    shell: ps aux | grep [c]lickhouse
