- name Add clickhouse addresses to etchosts
  become true
  lineinfile
    dest etchosts
    regexp '.{{ item }}$'
    line {{ hostvars[item].ansible_host }} {{item}}
    state present
  when hostvars[item].ansible_host is defined
  with_items {{ groups.clickhouse }}  